npm/node-semver

- package.json
The repository is now under the ownership of npm's organization, so package.json should reflect that change
> fix github URL

- README.md
`semver.inc('1.2.3', 'pre', 'beta')`  actually returns 1.2.3-beta.0.
`semver.inc('1.2.3', 'prerelease', 'beta')`  actually returns 1.2.4-beta.0.
> Fix the wrong semver pre(release) beta example

- README.md
- range.bnf
The old BNF expands "nr"s as:
- 0, or
- 1-9 followed by **one** or more digit from 0-9
i.e. excludes non-zero single-digit numbers. It should be:
- 0, or
- 1-9 followed by **zero** or more digit from 0-9
> Fix Backus-Naur "nr" expansion (previous expansion forbade 1 to 9)

- README.md
- semver.js
- test/index.js
This adds the function `minSatisfying` which is a mirror of `maxSatisfying` i.e. it returns the *lowest* version in the range that satisfies the given range.  As you can see it's an exact copy of `minSatisfying` that simply reverses the sort order being passed to `.filter`
The need for this arose from trying to resolve multiple security advisories that have semver ranges for which the problem has been fixed.  It is valuable to be able to distill the minimum version needed to satisfy each of those ranges, to (as much as possible) mitigate the potential impact that updates would cause.
> add minSatisfying

- README.md
- bin/semver
- semver.js
- test/coerce.js
Added the ability to coerce a string to semver before validation. This applies both to the CLI (via the -c,--coerce option) and the module (via the coerce function).
> Added version coercion to the module and CLI.

- README.md
This *might* be wrong, so please let me know!
I took the `| ` in this line to be the "with no operation" case, but the rule right above has
simple     ::= primitive | partial | tilde | caret
so, the "no operator" case is already covered. This makes me think the `|  ` was a typo, so it should be removed.
> Fix grammar for ranges

- ranges/subset.js
- test/ranges/subset.js
An "ANY" range (ie, `""`, `*`, etc.) does not include prerelease
versions except when `includePrerelease` flag is set.
Also, merely looking at the max/min boundaries of any ranges ignores the
fact that the sub range maybe including prerelease versions that are
excluded from the super range.  For example, `>=1.2.3-pre.0` is _not_ a
subset of `>=1.0.0`, because it inludes `1.2.3-pre.0`, `1.2.3-pre.1`,
and so on.
---
@jameschensmith, if you would be so kind as to give this a look over, and make sure it fixes the bug you found, I would greatly appreciate it.  Thanks!
Related to #374, #375 (includes the patch from #375).
> Correctly handle prereleases/ANY ranges in subset

- classes/range.js
Found in #433, the regex used to split ranges on `||` was padded by `\s*`
on either side causing a decrease in performance when used on range
strings with a lot of spaces. Since the result of the split is
immediately trimmed, we can just split on the string instead.
> fix: replace regex used to split ranges

- classes/range.js
- internal/re.js
- test/classes/range.js
- test/fixtures/range-parse.js
- test/ranges/valid.js
Previously the dots were not properly escaped causing them to match any
character. This caused ranges like `>=09090` to evaulate to `*` after
they were incorrectly matched by the `GTE0` regex. This only happened in
strict mode since in loose mode the leading 0 is allowed and parsed into
`>=9090.0.0` before the `GTE0` check. After this fix, this range now
will throw an error. This also affected prerelease versions in both
strict and loose mode.
> fix: properly escape dots in `GTE0` regexes

- test/map.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> fix: replace deprecated String.prototype.substr()

- bin/semver.js
- tap-snapshots/test/bin/semver.js.test.cjs
- test/bin/semver.js
> fix(bin): get correct value from arg separated by equals

- classes/semver.js
- test/fixtures/increments.js
The [semver spec](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) says prerelease can be numeric:
```
<pre-release identifier> ::= <alphanumeric identifier>
| <numeric identifier>
```
This PR fixes `inc` `prerelease` with numeric `preid`.
E.g. `inc('1.0.0-1.0', 'prerelease', '1')` should return `1.0.0-1.1`, but today it returns `1.0.0-1.0`.
The bug is that currently it compares preid with `this.prerelease[0] === identifier`, and a string `'1'` is not equal to number `1`, thus it's returning incorrect result. Change this comparison to use `compareIdentifiers` just like everywhere else fixes the problem.
- Fixes https://github.com/npm/cli/issues/3181
> fix: inc prerelease with numeric preid

- functions/inc.js
- test/functions/inc.js
`inc` can be used three ways:
1.  As a an option on the CLI : `npx semver 1.0.0 -i major`
2.  As a method of the `SemVer` class: `semverInstance.inc('major')`
3.  As a function: `inc('1.0.0', 'major')`
This PR does not impact the behaviour of the first two and focuses only on the last one.
The underlying issue is described in #425, but tl;dr `inc` should be a pure function (I think, from its documentation on NPM), and here it has a side-effect.
I remove this side-effect by ensuring that the `SemVer` instance created inside the `inc` function is created from a string, which removes the mutation vector.
Depends on #426 - just to fix the tests, that's why https://github.com/npm/node-semver/commit/563d75e3b5c10ee72c3d05c38c55c8a0e6c83c98 is polluting the changeset
Fixes #425
> fix: ensure SemVer instance passed to inc are not modified

- classes/range.js
Update range.js comments to clarify the caret examples
Caret (^) - does not modify the left-most non-zero element in the M.m.p-e. Tilde (~) - does not modify M and m.
hence, ^0.0.1-1 matches 0.0.1-5
however, ~0.0.1-1 matches 0.0.5
which might be counterintuitive and hence adding this example explicitly.
> docs: update range.js comments to clarify the caret ranges examples

- index.js
This is an alternative to https://github.com/npm/node-semver/pull/325/
Node.js now supports ESM named exports via auto-detection, but the way `node-semver` was creating `module.exports` was breaking that algorithm. The advantage of this approach is that there is no need for a wrapper file or for `package.exports`. It should be completely Semver Minor
This is a minor tweak to the layout of `index.js` that allows for ESM named exports support in all modern Node.js ESM implementations.
We could borrow the tests from #325, but it it a bit obtuse to add a single test to the testing framework as there is a 1:1 file to test expectation.
> fix: add support for node.js esm auto exports

- functions/diff.js
Based on the comment here: https://github.com/npm/node-semver/pull/533#issuecomment-1499798190
The performance before:
```
diff(0.0.1, 0.0.1-pre) x 310,595 ops/sec ±1.86% (94 runs sampled)
diff(0.0.1, 0.0.1-pre-2) x 317,054 ops/sec ±0.33% (92 runs sampled)
diff(1.1.0, 1.1.0-pre) x 304,229 ops/sec ±1.80% (86 runs sampled)
```
After:
```
diff(0.0.1, 0.0.1-pre) x 480,421 ops/sec ±0.86% (96 runs sampled)
diff(0.0.1, 0.0.1-pre-2) x 471,080 ops/sec ±0.99% (94 runs sampled)
diff(1.1.0, 1.1.0-pre) x 476,067 ops/sec ±0.98% (95 runs sampled)
```
<details>
<summary>benchmark.js</summary>
```js
const Benchmark = require('benchmark')
const diff = require('./functions/diff')
const suite = new Benchmark.Suite()
const cases = [
['0.0.1', '0.0.1-pre', 'patch'],
['0.0.1', '0.0.1-pre-2', 'patch'],
['1.1.0', …
```
> fix: faster diff

- ranges/subset.js
As I comment here: https://github.com/npm/node-semver/pull/528#issuecomment-1499241387
The method of subset was creating comparators without needing for a specific ranges, perf:
```
subset(1.2.3, *) x 208,363 ops/sec ±1.01% (93 runs sampled)
subset(^1.2.3, *) x 238,678 ops/sec ±1.08% (91 runs sampled)
subset(^1.2.3-pre.0, *) x 235,344 ops/sec ±1.12% (92 runs sampled)
subset(^1.2.3-pre.0, *) x 238,530 ops/sec ±0.97% (96 runs sampled)
subset(1 || 2 || 3, *) x 117,125 ops/sec ±0.83% (93 runs sampled)
```
After caching those comparators:
```
subset(1.2.3, *) x 241,957 ops/sec ±0.78% (93 runs sampled)
subset(^1.2.3, *) x 277,689 ops/sec ±1.02% (93 runs sampled)
subset(^1.2.3-pre.0, *) x 278,444 ops/sec ±1.29% (95 runs sampled)
subset(^1.2.3-pre.0, *) x 278,750 ops/sec ±0.99% (94 runs sampled) …
```
> fix: reuse comparators on subset

- functions/diff.js
- test/functions/diff.js
Cleanup of #334 
Closes #333
Authored by @deefactorial
> fix: semver.diff prerelease to release recognition

- functions/parse.js
I saw these lines that check if the version is valid and I thought, what if we remove it?
https://github.com/npm/node-semver/blob/f66cc45c6e82eebb4b5b51af73e7b8dcaeda7e21/functions/parse.js#L21-L24
Well, the perf before:
```
parse(1.2.1) x 2,282,718 ops/sec ±1.53% (94 runs sampled)
parse(1.2.2-4) x 917,890 ops/sec ±0.79% (88 runs sampled)
parse(1.2.3-pre) x 878,671 ops/sec ±1.07% (91 runs sampled)
invalid parse(90071992547409910.0.0) x 76,913 ops/sec ±0.97% (91 runs sampled)
invalid parse(hello, world) x 27,848,607 ops/sec ±2.58% (89 runs sampled)
invalid parse(xyz) x 28,323,638 ops/sec ±2.53% (88 runs sampled)
```
Then:
```
parse(1.2.1) x 2,758,186 ops/sec ±1.72% (94 runs sampled)
parse(1.2.2-4) x 990,634 ops/sec ±0.63% (93 runs sampled)
parse(1.2.3-pre) x 988,248 ops/sec ±1.12% (94 runs …
```
> fix: optimistic parse

- bin/semver.js
- classes/comparator.js
- functions/parse.js
- internal/parse-options.js
- test/internal/parse-options.js
The performance of parse-options before:
```
includePrerelease x 12,935,785 ops/sec ±3.66% (80 runs sampled)
includePrerelease + loose x 6,915,009 ops/sec ±1.54% (85 runs sampled)
includePrerelease + loose + rtl x 7,350,781 ops/sec ±1.54% (88 runs sampled)
```
After:
```
includePrerelease x 1,122,022,296 ops/sec ±0.81% (96 runs sampled)
includePrerelease + loose x 1,133,747,998 ops/sec ±0.11% (89 runs sampled)
includePrerelease + loose + rtl x 1,135,218,097 ops/sec ±0.35% (95 runs sampled)
```
The performance improvement also extend for any method that use `parseOptions`, like `satisfies`:
Before:
```
satisfies(1.0.6, 1.0.3||^2.0.0) x 281,862 ops/sec ±2.84% (89 runs sampled)
satisfies(1.0.6, 2.2.2||~3.0.0) x 312,593 ops/sec ±0.90% (95 runs sampled)
satisfies(1.0.6, 2.3.0||<4.0.0) x …
```
> fix: faster parse options

- classes/comparator.js
- ranges/intersects.js
- test/classes/comparator.js
- test/fixtures/comparator-intersection.js
- test/ranges/intersects.js
Also fix options not being passed through from semver.intersects
Closes https://github.com/npm/node-semver/issues/521
> fix: intersects with v0.0.0 and v0.0.0-0

- functions/diff.js
Following https://github.com/npm/node-semver/pull/539 this small change improves speed by ~10% just calling `compare` directly on the semver object returned by parse
Performance on branch v7.4.0
```
╭─macno@cayenne ~/Projects/opensource/node-semver  ‹v7.4.0›
╰─➤  node benchmark.js
diff(0.0.1, 0.0.1) x 4,290,326 ops/sec ±0.34% (95 runs sampled)
diff(0.0.1, 0.0.1-pre) x 2,136,948 ops/sec ±0.06% (94 runs sampled)
diff(0.0.1, 0.0.1-pre-2) x 2,123,307 ops/sec ±0.12% (95 runs sampled)
diff(1.1.0, 1.1.0-pre) x 2,124,436 ops/sec ±0.12% (102 runs sampled)
```
And after the change
```
╭─macno@cayenne ~/Projects/opensource/node-semver  ‹main›
╰─➤  node benchmark.js
diff(0.0.1, 0.0.1) x 4,801,698 ops/sec ±0.30% (90 runs sampled)
diff(0.0.1, 0.0.1-pre) x 2,323,553 ops/sec ±0.06% (98 runs sampled) …
```
> fix: avoid re-instantiating SemVer during diff compare

- classes/semver.js
- functions/diff.js
- functions/parse.js
- test/functions/diff.js
- test/functions/parse.js
The parsing logic that is duplicated in SemVer's constructor was also removed.  See #541 for previous discussions about not optimizing for invalid SemVer.
With this fix:
```javascript
> semver.diff('foo', '1.2.3')
Uncaught TypeError: Invalid Version: foo
```
`v7.4.0`:
```javascript
> semver.diff('foo', '1.2.3')
Uncaught TypeError: Invalid Version: null
```
`503a4e52`:
```javscript
> semver.diff('foo', '1.2.3')
Uncaught TypeError: Cannot read properties of null (reading 'compare')
```
> fix: throw on bad version with correct error message

- classes/semver.js
- test/classes/semver.js
- test/fixtures/increments.js
- test/functions/inc.js
> fix: preserve build in raw after inc

- README.md
Adds an example clarifying how greater-than comparator works.
Closes #275
> docs: add example for `>` comparator

- internal/re.js
- test/functions/valid.js
> fix: correctly parse long build ids as valid

- semver.js
- test/index.js
- test/re.js
- test/whitespace.js
This is a backport of the following commits squashed to land on
`release/v6`:
- 717534e
- abdd93d
- cc6fde2
- 99d8287
Ref: #564
> fix: better handling of whitespace (backport to v6)

- semver.js
- test/index.js
- test/re.js
- test/whitespace.js
This backports the security fix https://github.com/npm/node-semver/pull/564 to v5.
> fix: better handling of whitespace (backport to v5)

- README.md
- functions/coerce.js
- internal/re.js
- test/functions/coerce.js
Introduces the new coerce option `includePrerelease`, if set, allowing to preserve pre-release and build parts of a version.
Fixes #592
Fixes #357
> feat: preserve pre-release and build parts of a version on coerce (#592)

- classes/semver.js
Correcting the debug message in `compareBuild`
> fix: typo in compareBuild debug message

- README.md
- Fix spelling, grammar, and consistency of README text (based on grammarly recommendations)
- Remove unnecessary phrases and commas
- Improve consistency of `js` example code
- Add documentation of `identifier` and `identifierBase` parameters for `inc` function
- Add missing documentation of `compareLoose`, `sort`, and `rsort` functions
- Add `simplify` and `subset` to list of module exports
> chore: various improvements to README

- .gitignore
- benchmarks/bench-compare.js
- benchmarks/bench-diff.js
- benchmarks/bench-parse-options.js
- benchmarks/bench-parse.js
- benchmarks/bench-satisfies.js
- benchmarks/bench-subset.js
- package.json
I had these benchmarks from the last time I did some perf research in this repo, so I thought maybe it was a good idea to have them in the repo itself, so other people can use them and you guys can verify if the perf is still good or you had any regression.
> chore: add benchmarks

- bin/semver.js
- classes/range.js
- internal/lrucache.js
- package.json
- test/classes/range.js
- test/internal/lrucache.js
This is a rebase of https://github.com/npm/node-semver/pull/697 to
isolate the changes into two discrete commits.
- **deps: remove lru-cache**
- **fix: use internal cache implementation**
> replace lru-cache dependency

- package.json
#704 removed usage of `lru-cache`, but the dependency wasn't removed from `package.json`
Related to #704
> deps: uninstall `lru-cache`

- internal/lrucache.js
The default implementation already returns boolean if the value has been deleted.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete#return_value
It's also faster since we don't double check the hashmap for a value.
> fix(lru): use map.delete() directly

- README.md
This is just a typo correction. Thanks for the awesome project!
> docs: fix extra backtick typo

- classes/range.js
- test/classes/range.js
This pull request optimizes the Range class in the following ways:
1. Produce fewer intermediate objects when reducing a range's space characters to single spaces. This seems to improve bench-subset scores by up to 5%, and bench-satisfies scores to a lesser degree.
2. Optimize Range formatting with explicit for loops instead, avoiding an intermediate array creation. This seems to improve bench-satisfies and bench-subset scores by up to 20%.
3. Calculate Range's `.range` string (used by `.format()` and `.toString()`) lazily. This seems to improve bench-satisfies and bench-subset scores by up to 9%.
The external interface for the class stays the same, except for the new internal `.formatted` property used to cache its lazily calculated string. `Range#range` property is now also read-only. …
> fix: optimize Range parsing and formatting

- README.md
Adds an explanation why the "=" and "v" prefixes should not be used anymore.
> docs: clarify comment about obsolete prefixes

- README.md
Added a missing period in specific parts of the text to maintain consistency across the document. This ensures a uniform writing style, improves readability, and aligns with the formatting used throughout the content.
> docs(readme): added missing period for consistency

- README.md
- bin/semver.js
- classes/semver.js
- tap-snapshots/test/bin/semver.js.test.cjs
- test/fixtures/increments.js
Here's the `release` options for `inc`. Includes update to docs and a few tests.
Closes #740
> feat: add "release" inc type

- classes/semver.js
- test/classes/semver.js
- test/fixtures/increments.js
- Adds a check of the `identifier` parameter for `inc()` when trying to increase pre-releases. This prevents the creation of an invalid semver.
- Removes side-effects of `inc()` when it is throwing (it was changing the version)
Closes #349
> fix: add identifier validation to `inc()`

- functions/diff.js
- test/functions/diff.js
Refactored version diff logic to handle transitions from prerelease versions to stable versions correctly for major/minor/patch version bumps.
Closes #606
> fix(diff): fix prerelease to stable version diff logic

- classes/semver.js
- internal/re.js
- test/fixtures/increments.js
- test/internal/re.js
Closes: https://github.com/npm/node-semver/issues/763
> fix(inc): fully capture prerelease identifier

- benchmarks/bench-compare.js
- benchmarks/bench-parse.js
- classes/semver.js
- internal/identifiers.js
- test/internal/identifiers.js
A simple change to avoid Regex when we already know both values are number.
```diff
-compare 0.0.0 to 0.0.0-foo x 2,281,198 ops/sec ±0.36% (98 runs sampled)
+compare 0.0.0 to 0.0.0-foo x 3,020,851 ops/sec ±0.38% (99 runs sampled)
-compare 0.0.1 to 0.0.0 x 3,874,114 ops/sec ±0.53% (94 runs sampled)
+compare 0.0.1 to 0.0.0 x 5,925,824 ops/sec ±0.28% (99 runs sampled)
-compare 1.0.0 to 0.9.9 x 4,764,980 ops/sec ±0.62% (94 runs sampled)
+compare 1.0.0 to 0.9.9 x 5,837,427 ops/sec ±0.38% (97 runs sampled)
-compare 0.10.0 to 0.9.0 x 3,799,602 ops/sec ±0.49% (94 runs sampled)
+compare 0.10.0 to 0.9.0 x 5,390,337 ops/sec ±0.40% (98 runs sampled)
-compare 0.99.0 to 0.10.0 x 3,457,321 ops/sec ±0.54% (94 runs sampled)
+compare 0.99.0 to 0.10.0 x 4,729,216 ops/sec ±0.25% (101 runs sampled)
-compare …
```
> fix: faster paths for compare
